version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "12:00"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
