name: Release

on:
  release:
    types: [published]

env:
  PYTHON_VERSION: "3.11"

permissions: {}

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Hatch
        run: python3 -m pip install hatch
      - name: Install dependencies
        run: hatch build
      - name: Publish to PyPi
        if: startsWith(github.ref, 'refs/tags/')
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.RUFF_LSP_TOKEN }}
        run: |
          hatch publish
